language: cpp
dist: trusty
script:
   - CXX=g++-6 cmake -DUSE_PYTHON_BINDINGS=ON -DENABLE_COVERAGE:BOOL=TRUE .
   - make -j 2
   - make test
   - bash <(curl -s https://codecov.io/bash)
   
sudo: false
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - libboost-python-dev
         - g++-6
         - binutils-gold
